//requirejs 打包
var requirejs = {
  "options": {
    baseUrl                : "<%= config.SRC_DIR %>",
    preserveLicenseComments: false,
    optimize               : "none"
  },

  libs: {
    options: {
      paths  : {
        "json2"               : "3rdlibs/json2",
        "bridge"              : "3rdlibs/bridge",
        "R"                   : "3rdlibs/require",
        "$"                   : "3rdlibs/zepto",
        "_"                   : "3rdlibs/underscore",
        "B"                   : "3rdlibs/backbone",
        "F"                   : "3rdlibs/fastclick",
        "libs"                : "3rdlibs/libs",
        "text"                : "3rdlibs/require.text",
        "cHybridFacade"       : "app/hybrid/c.hybrid.facade",
        "cHybridShell"        : "app/hybrid/c.hybrid.shell",
        "cGeoHelper"          : "service/web/c.geo.helper",
        "cGeo"                : "common/c.geo",
        "cCommonStore"        : "http://0",
        "cShell"              : "shell/c.shell",
        "cShell_CTRIP_MASTER" : "shell/c.shell.ctrip.master",
        "cShell_TECENT_WEIXIN": "shell/c.shell.tecent.weixin"
      },
      include: [
        "bridge",
        "R",
        "$",
        "_",
        "B",
        "F",
        "libs",
        "text",
        "cHybridFacade",
        "cHybridShell",
        "cGeoHelper",
        "cGeo",
        "cShell",
        "cShell_CTRIP_MASTER",
        "cShell_TECENT_WEIXIN"
      ],
      out    : "<%= config.JS_TEMP_DIR %>/libs/lizard.libs.js"
    }
  },

  common: {
    options: {
      paths  : {
        "json2" : "3rdlibs/json2",
        "bridge": "3rdlibs/bridge",
        "R"     : "3rdlibs/require",
        "$"     : "3rdlibs/zepto",
        "_"     : "3rdlibs/underscore",
        "B"     : "3rdlibs/backbone",
        "F"     : "3rdlibs/fastclick",
        "libs"  : "3rdlibs/libs",
        "text"  : "3rdlibs/require.text",

        "cCoreInherit": "common/c.class.inherit",

        "cBusinessCommon": "app/c.app.interface",

        "cMessageCenter": "common/c.message.center",
        "cAjax"       : "common/c.ajax",
        "cImgLazyload": "common/c.img.lazyload",

        "cPageParser": "app/c.page.parser",
        "cPageModelProcessor": "app/c.page.model.processor",
        "cParserUtil"        : "app/c.parser.util",

        "cPageView": "page/c.page.view",
        "cPageList": "page/c.page.list",

        "cUtilCacheView": "util/c.util.cacheview",
        "cUtilCommon"     : "util/c.util.common",
        "cUtilDate"       : "util/c.util.date",
        "cUtilHybrid"     : "util/c.util.hybrid",
        "cUtilObject"     : "util/c.util.object",
        "cUtilPath"       : "util/c.util.path",
        "cUtilPerformance": "util/c.util.performance",
        "cUtilValidate"   : "util/c.util.validate",
        "cUtilCryptBase64": "util/crypt/c.crypt.base64",
        "cUtilCryptRSA"   : "util/crypt/c.crypt.rsa",

        "cAbstractStore": "data/store/c.abstract.store",
        "cLocalStore"      : "data/store/c.local.store",
        "cSessionStore"    : "data/store/c.session.store",
        "cMemoryStore"     : "data/store/c.memory.store",
        "cCommonStore"     : "data/store/c.common.store",
        "cHeadStore"       : "data/store/common/c.head.store",
        "cUserStore"       : "data/store/common/c.user.store",
        "cMarketStore"     : "data/store/common/c.market.store",
        "cMobileTokenStore": "data/store/common/c.mobiletoken.store",

        "cAbstractStorage": "data/storage/c.abstract.storage",
        "cLocalStorage"  : "data/storage/c.local.storage",
        "cSessionStorage": "data/storage/c.session.storage",
        "cMemoryStorage" : "data/storage/c.memory.storage",

        "cAbstractModel": "data/model/c.abstract.model",
        "cModel"    : "data/model/c.model",
        "cUserModel": "data/model/c.user.model",

        "cUIBase": "ui/c.ui.base",
        "UIView"         : "ui/ui.abstract.view",
        "UILayer"        : "ui/ui.layer",
        "UIAlert"        : "ui/ui.alert",
        "UIMask"         : "ui/ui.mask",
        "UILoading"      : "ui/ui.loading",
        "UILoadingLayer" : "ui/ui.loading.layer",
        "UIToast"        : "ui/ui.toast",
        "UIInlineView"   : "ui/ui.inline.view",
        "UINum"          : "ui/ui.num",
        "UISwitch"       : "ui/ui.switch",
        "UIBubbleLayer"  : "ui/ui.bubble.layer",
        "UITab"          : "ui/ui.tab",
        "UIScroll"       : "ui/ui.scroll",
        "UIScrollLayer"  : "ui/ui.scroll.layer",
        "UIRadioList"    : "ui/ui.radio.list",
        "UISelect"       : "ui/ui.select",
        "UIGroupSelect"  : "ui/ui.group.select",
        "UIGroupList"    : "ui/ui.group.list",
        "UICalendar"     : "ui/ui.calendar",
        "UISlider"       : "ui/ui.slider",
        "UIImageSlider"  : "ui/ui.image.slider",
        "cUIInputClear"  : "ui/c.ui.input.clear",
        "UIWarning404"   : "ui/ui.warning404",
        "UIHeader"       : "ui/ui.header",
        "UIIdentitycard" : "ui/ui.identitycard",
        "UILayerList"    : "ui/ui.layer.list",
        "UIAnimation"    : "ui/c.ui.animation",
        "UITemplates"    : "ui/ui.templates",
        "cCommonListPage": "ui/c.page.common.list",

        "cGeoService": "service/c.service.geo",
        "cMemberService": "service/c.service.member",
        "cGuiderService": "service/c.service.guider",
        "cQrcodeService": "service/c.service.qrcode",

        "cHybridMember": "service/hybrid/c.hybrid.memberService",
        "cHybridGuider"     : "service/hybrid/c.hybrid.guider",
        "cHybridGeolocation": "service/hybrid/c.hybrid.geolocation",
        "cPadExtend":     "app/c.pad.extend",

        "text!ui/ui.alert.html": "http://1",
        "text!ui/ui.bubble.layer.html": "http://2",
        "text!ui/ui.calendar.html"    : "http://3",
        "text!ui/ui.group.list.html"  : "http://4",
        "text!ui/ui.group.select.html": "http://5",
        "text!ui/ui.loading.html"     : "http://6",
        "text!ui/ui.mask.html"        : "http://7",
        "text!ui/ui.num.html"         : "http://8",
        "text!ui/ui.radio.list.html"  : "http://11",
        "text!ui/ui.reloading.html"   : "http://12",
        "text!ui/ui.scroll.layer.html": "http://13",
        "text!ui/ui.select.html"      : "http://14",
        "text!ui/ui.slider.html"      : "http://15",
        "text!ui/ui.switch.html"      : "http://16",
        "text!ui/ui.tab.html"         : "http://17",
        "text!ui/ui.toast.html"       : "http://18",
        "text!ui/ui.header.html"      : "http://19",
        "text!ui/ui.warning404.html"  : "http://10",

        "text!ui/ui.identitycard.html": "http://110",
        "text!ui/ui.layer.list.html"     : "http://120",
        "text!ui/ui.emotion.loading.html": "http://130",

        "cStatic": "app/web/c.web.static",
        "cHybridApp"  : "app/hybrid/c.hybrid.app",
        "cBaseInit"   : "app/c.base.init",
        "cAbstractApp": "app/c.abstract.app",

        "config": "config",
        "seed"          : "lizard.seed",
        "cHybridStart"  : "app/hybrid/c.hybrid.start",
        "cHybridHeader" : "app/hybrid/c.hybrid.header",
        "cHybridAppInit": "app/hybrid/c.hybrid.init",

        "cPlugins": "plugins/c.plugins",
        "cJsonPlugin"      : "plugins/c.json.plugin",
        "cMarketPlugin"    : "plugins/c.market.plugin",
        "cSafariPlugin"    : "plugins/c.safari.plugin",
        "cStatisticsPlugin": "plugins/c.statistics.plugin",
        "cUnderscorePlugin": "plugins/c.underscore.plugin",
        "cZeptoPlugin"     : "plugins/c.zepto.plugin",

        "cHybridFacade": "http://cHybridFacade",
        "cHybridShell": "http://app/hybrid/c.hybrid.shell",

        "loading"          : "http://webresource.c-ctrip.com/ResCRMOnline/R5/basewidget/ui.load",
        "loadFailed"       : "http://webresource.c-ctrip.com/ResCRMOnline/R5/basewidget/ui.loadFailed"
      },
      include: [
        "seed",
        "config",
        "cHybridStart",

        "cCoreInherit",

        "cMessageCenter",
        "cAjax",
        "cImgLazyload",
        "cPageParser",
        "cParserUtil",
        "cUtilCacheView",
        "cUtilCommon",
        "cUtilDate",
        "cUtilHybrid",
        "cUtilObject",
        "cUtilPath",
        "cUtilPerformance",
        "cUtilValidate",
        "cUtilCryptBase64",
        "cUtilCryptRSA",

        "cAbstractStore",
        "cLocalStore",
        "cSessionStore",
        "cMemoryStore",
        "cCommonStore",

        "cAbstractStorage",
        "cLocalStorage",
        "cSessionStorage",

        "cAbstractModel",
        "cModel",
        "cUserModel",

        "cUIBase",
        "UIView",
        "UILayer",
        "UIAlert",
        "UIMask",
        "UILoading",
        "UILoadingLayer",
        "UIToast",
        "UIInlineView",
        "UINum",
        "UISwitch",
        "UIBubbleLayer",
        "UITab",
        "UIScroll",
        "UIScrollLayer",
        "UIRadioList",
        "UISelect",
        "UIGroupSelect",
        "UIGroupList",
        "UICalendar",
        "UISlider",
        "UIImageSlider",
        "cUIInputClear",
        "UIWarning404",
        "cHybridHeader",
        "UIIdentitycard",
        "UILayerList",
        "UIAnimation",

        "text!ui/ui.alert.html",
        "text!ui/ui.bubble.layer.html",
        "text!ui/ui.calendar.html",
        "text!ui/ui.group.list.html",
        "text!ui/ui.group.select.html",
        "text!ui/ui.loading.html",
        "text!ui/ui.mask.html",
        "text!ui/ui.num.html",
        "text!ui/ui.radio.list.html",
        "text!ui/ui.loading.layer.html",
        "text!ui/ui.scroll.layer.html",
        "text!ui/ui.select.html",
        "text!ui/ui.slider.html",
        "text!ui/ui.switch.html",
        "text!ui/ui.tab.html",
        "text!ui/ui.toast.html",
        "text!ui/ui.header.html",
        "text!ui/ui.warning404.html",
        "text!ui/ui.emotion.loading.html",
        "text!ui/ui.identitycard.html",
        "text!ui/ui.layer.list.html",
        "cPageView",
        "cPageList",
        "cMemberService",
        "cGuiderService",
        "cGeoService",
        "cQrcodeService",

        "cStatic",
        "cBaseInit",
        "cHybridAppInit",
        "cAbstractApp",
        "cHybridApp",
        "cHybridHeader",
        "cHybridMember",
        "cHybridGuider",
        "cHybridGeolocation",

        "cPlugins",
        "cJsonPlugin",
        "cMarketPlugin",
        "cSafariPlugin",
        "cStatisticsPlugin",
        "cUnderscorePlugin"
      ],
      "out"  : "<%= config.JS_TEMP_DIR %>/<%= config.LIZARD_VERSION%>/web/lizard.common.js"
    }
  }
};